### ISSUE TITLE
Broken LUIv3

### ISSUE THREAD

**Issue by Mithras2801** [FireSiku/Legacy-LUI#1]
Hello,
https://imgur.com/a/VjHr7NG

On screens:
Yellow: Cant move addon Omen
Blue: Details cant on
Brown: No compatibility with sexy map On bfa yes compatybility. Location near center up map
Red: Cant off it i use skin LUI no other

**Comment by FireSiku** [comment]
The prepatch broke a lot of addons. Please make sure these addons are up to date and that their authors have released changes to make them compatible with Shadowlands. Do these addons work as expected if LUI is turned off?

In regards to the red circle, are you trying to use LUI unitframes or a 3rd party unitframes?
