### ISSUE TITLE
Where are the settings for other character stored?

### ISSUE THREAD

**Issue by Vagooba** [FireSiku/Legacy-LUI#4]
I'm trying to find the profile file for my other character so i can send it to my friend so my friend can use it aswell.
By profile file i mean, when you select a profile your characters appear and you can slect thoes profile settings, is there a physical file that i can aquire somewhere and send it to my friend so it can be used on another account?
Is this possible?

**Comment by jewebr** [comment]
Settings are saved in `\World of Warcraft\_retail_\WTF\Account\ACCOUNTNAME\SavedVariables\LUI.lua`
Be sure to backup your own and you're friend his `WTF` folder before you start overwriting files.
Sorry for the late reply.
